Unit testing
XsidX/oop_school_library pull request #7
Opened 2022-10-06 10:57 UTC by AbdollahRaafat

In this project, We add unit tests to our codebase, specifically our classes.

2022-10-06 11:28 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @XsidX, @AbdollahRaafat, and @Roseokpe👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 11:28 UTC, thecodechaser commented on spec/book_spec.rb
> +
- [ ] There's a problem with importing classes on test files and I'm getting errors when I run the tests. `require` looks for files from the root directory, not the current directory. To go with the current directory you should use `require_relative` or you can assume importing as from the root directory like `require './classes/book'`. Please fix this issue for all the test files.

![image](https://user-images.githubusercontent.com/83803414/194300694-aae76883-e03b-4a86-8693-a4aca4582227.png)

2022-10-06 11:28 UTC, thecodechaser commented on spec/book_spec.rb
> +  end
- [ ] 5 out of 8 tests are failing, Please make sure that all tests pass successfully.

![image](https://user-images.githubusercontent.com/83803414/194301116-7b8d09c4-51db-4e28-bbf9-ed770c6db5bc.png)

2022-10-06 14:53 UTC, FrederickMih requested changes
Hi @AbdollahRaafat , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://media.giphy.com/media/uVgohq4sCg1Uc/giphy.gif)


 ## Highlights

-  Gitflow has been followed :+1: 
-  No Linter error :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 14:53 UTC, FrederickMih commented on spec/classroom_spec.rb
> +describe Classroom do
- [ ] Seems you still have a failing test. Kindly fix :wrench: it.


![Screenshot from 2022-10-06 15-48-44](https://user-images.githubusercontent.com/63087491/194345102-33aa40f8-5120-4efc-a5b3-2c4dc4905bae.png)

2022-10-07 09:14 UTC, julie-ify approved these changes
Hi Team,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 09:30 UTC, merged